name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Show files
        run: cmd /c dir build /s

      - name: Package
        shell: powershell
        run: |
          Copy-Item build\bin\NormalToHeight.exe build\bin\

          Get-ChildItem -Recurse build -Filter *.dll |
            Copy-Item -Destination build\bin

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: NormalToHeight-windows
          path: build/bin
